import { Box, Container, Stack } from "@mui/material";
import type { Metadata } from "next";
import Footer from "./common/Footer";
import Header from "./common/headers/Header";
import { SWRProvider } from "./swr/SwrProvide";
import ThemeRegistry from "./theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <SWRProvider>
            <Stack minHeight={"100vh"}>
              <Header />
              <Box component={"main"} flexGrow={1}>
                {children}
              </Box>
              <Footer />
            </Stack>
          </SWRProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
